<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>UnityRuntimeMCP</AssemblyName>
    <Product>UnityRuntimeMCP</Product>
    <Version>1.0.5</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://nuget.bepinex.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.755" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="libs\*.dll">
      <HintPath>libs\%(RecursiveDir)%(FileName)%(Extension)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="src\WebUI\**\*" />
  </ItemGroup>

</Project>
